---
  - hosts: all
    tasks:
    - name: Copy & Create File.
      copy:
       dest: /root/script.sh
       content: |
       # A simple variable example
       greeting=Hello
       name=Team
       echo $greeting $name

    - name: Run Shell Script.
      shell: sh /root/script.sh

    - name: Remove Shell Script
      file:
       path: /root/script.sh
       state: absent